name: flutter_api_bloc_codegen
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0
  retrofit: ^4.4.2
  flutter_bloc: ^9.0.0
  freezed_annotation: ^2.2.0
  flutter_easyloading: ^3.0.5
  hive: ^2.2.3
  path_provider: ^2.1.5
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_annotation: ^4.9.0
  retrofit_generator: ^9.1.9
  json_serializable: ^6.9.4
  freezed: ^2.3.2

flutter:

  uses-material-design: true
